[[redirects]]
  from = "/books/*.html"
  to = "/books/:splat"

[[redirects]]
  from = "/rest-and-hypermedia-in-2019-76cb3421e745"
  to = "/blog/rest-and-hypermedia-in-2019"

[[redirects]]
  from = "/resolving-overloaded-terms-for-api-specifications-descriptions-contracts-c31a6d44d269"
  to = "/blog/resolving-overloaded-terms-for-api-specifications-descriptions-contract"

[[redirects]]
  from = "/organizing-your-asyncapi-documents-4bedc1b3eb05"
  to = "/blog/organizing-your-asyncapi-documents"

[[redirects]]
  from = "/caching-is-hard-draw-me-a-picture-updated-cdb354cbf3d0"
  to = "/blog/caching-is-hard-draw-me-a-picture"

[[redirects]]
  from = "/a-happy-compromise-between-customization-and-cacheability-*"
  to = "/blog/partials-happy-compromise-between-customization-and-cacheability"

[[redirects]]
  from = "/useful-api-errors-for-rest-graphql-and-grpc-*"
  to = "/blog/creating-good-api-errors-in-rest-graphql-and-grpc"

[[redirects]]
  from = "/taking-a-timeout-from-poor-performance-473965255009"
  to = "/blog/taking-a-timeout-from-poor-performance"

[[redirects]]
  from = "/weworks-api-specification-workflow-defec45cc037"
  to = "/blog/weworks-api-specification-workflow"

[[redirects]]
  from = "/api-versioning-has-no-right-way-*"
  to = "/blog/api-versioning-has-no-right-way"

[[redirects]]
  from = "/api-evolution-for-rest-http-apis-*"
  to = "/blog/api-evolution-for-rest-http-apis"

[[redirects]]
  from = "/common-hypermedia-patterns-with-json-hyper-schema-*"
  to = "/blog/common-hypermedia-patterns-with-json-hyper-schema"

[[redirects]]
  from = "/creating-api-specifications-from-bulls-t-*"
  to = "/blog/creating-api-specifications-from-bullst"

[[redirects]]
  from = "/getting-started-with-json-hyper-schema-*"
  to = "/blog/getting-started-with-json-hyper-schema"

[[redirects]]
  from = "/getting-started-with-json-hyper-schema-part-2-*"
  to = "/blog/getting-started-with-json-hyper-schema-part-2"

[[redirects]]
  from = "/govern-your-apis-with-speccy-*"
  to = "/blog/govern-your-apis-with-speccy"

[[redirects]]
  from = "/graphql-vs-rest-caching-*"
  to = "/blog/graphql-vs-rest-caching"

[[redirects]]
  from = "/graphql-vs-rest-overview-*"
  to = "/blog/graphql-vs-rest-overview"

[[redirects]]
  from = "/guessing-api-contracts-*"
  to = "/blog/commit-to-api-contracts"

[[redirects]]
  from = "/health-checks-for-rest-grpc-apis-kubernetes-and-beyond-*"
  to = "/blog/health-checks-for-rest-grpc-apis-kubernetes-and-beyond"

[[redirects]]
  from = "/json-api-openapi-and-json-schema-working-in-harmony-*"
  to = "/blog/json-api-openapi-and-json-schema-working-in-harmony"

[[redirects]]
  from = "/keeping-documentation-honest-*"
  to = "/blog/keeping-documentation-honest"

[[redirects]]
  from = "/lets-stop-building-apis-around-a-network-hack-*"
  to = "/blog/lets-stop-building-apis-around-a-network-hack"

[[redirects]]
  from = "/making-the-most-of-json-api-*"
  to = "/blog/making-the-most-of-json-api"

[[redirects]]
  from = "/meet-the-api-community-*"
  to = "/blog/meet-the-api-community"

[[redirects]]
  from = "/openapi-and-json-schema-divergence-part-1-*"
  to = "/blog/openapi-and-json-schema-divergence-part-1"

[[redirects]]
  from = "/openapi-and-json-schema-divergence-part-2-*"
  to = "/blog/solving-openapi-and-json-schema-divergence"

[[redirects]]
  from = "/optimizing-for-the-speed-of-light-*"
  to = "/blog/optimizing-for-the-speed-of-light"

[[redirects]]
  from = "/picking-the-right-api-paradigm-*"
  to = "/blog/picking-the-right-api-paradigm"

[[redirects]]
  from = "/put-vs-patch-vs-json-patch-*"
  to = "/blog/put-vs-patch-vs-json-patch"

[[redirects]]
  from = "/remote-api-consulting-*"
  to = "/blog/remote-api-consulting"

[[redirects]]
  from = "/representing-state-in-rest-and-graphql-*"
  to = "/blog/representing-state-in-rest-and-graphql"

[[redirects]]
  from = "/speeding-up-apis-apps-smart-toasters-with-http-response-caching-*"
  to = "/blog/http-client-response-caching"

[[redirects]]
  from = "/surviving-deprecations-to-resources-and-properties-on-other-apis-9711e7def610"
  to = "/blog/surviving-deprecations-to-resources-and-properties-on-other-apis"

[[redirects]]
  from = "/the-many-amazing-uses-of-json-schema-client-side-validation-*"
  to = "/blog/the-many-amazing-uses-of-json-schema-client-side-validation"

[[redirects]]
  from = "/tricking-colleagues-into-writing-documentation-via-contract-testing-*"
  to = "/blog/writing-documentation-via-contract-testing"

[[redirects]]
  from = "/turning-contracts-into-beautiful-documentation-*"
  to = "/blog/turning-contracts-into-beautiful-documentation"

[[redirects]]
  from = "/understanding-rpc-rest-and-graphql-*"
  to = "/blog/understanding-rpc-rest-and-graphql"

[[redirects]]
  from = "/what-is-api-rate-limiting-all-about-*"
  to = "/blog/what-is-api-rate-limiting-all-about"

[[redirects]]
  from = "/why-do-people-dislike-json-*"
  to = "/blog/why-some-people-dislike-json"

[[redirects]]
  from = "/you-might-not-need-graphql-*"
  to = "/blog/you-might-not-need-graphql"
